In [64]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [67]:
df=pd.read_csv("dailyActivity_merged.csv")
df

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,04-12-2016,13162,8.500000,8.500000,0.0,1.88,0.55,6.06,0.00,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.970000,6.970000,0.0,1.57,0.69,4.71,0.00,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.740000,6.740000,0.0,2.44,0.40,3.91,0.00,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.280000,6.280000,0.0,2.14,1.26,2.83,0.00,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.160000,8.160000,0.0,2.71,0.41,5.04,0.00,36,10,221,773,1863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,8877689391,05-08-2016,10686,8.110000,8.110000,0.0,1.08,0.20,6.80,0.00,17,4,245,1174,2847
936,8877689391,05-09-2016,20226,18.250000,18.250000,0.0,11.10,0.80,6.24,0.05,73,19,217,1131,3710
937,8877689391,05-10-2016,10733,8.150000,8.150000,0.0,1.35,0.46,6.28,0.00,18,11,224,1187,2832
938,8877689391,05-11-2016,21420,19.559999,19.559999,0.0,13.22,0.41,5.89,0.00,88,12,213,1127,3832
939,8877689391,05-12-2016,8064,6.120000,6.120000,0.0,1.82,0.04,4.25,0.00,23,1,137,770,1849

In [98]:
df2=df.drop('Id',axis=1)
df2

,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,04-12-2016,13162,8.500000,8.500000,0.0,1.88,0.55,6.06,0.00,25,13,328,728,1985
1,4/13/2016,10735,6.970000,6.970000,0.0,1.57,0.69,4.71,0.00,21,19,217,776,1797
2,4/14/2016,10460,6.740000,6.740000,0.0,2.44,0.40,3.91,0.00,30,11,181,1218,1776
3,4/15/2016,9762,6.280000,6.280000,0.0,2.14,1.26,2.83,0.00,29,34,209,726,1745
4,4/16/2016,12669,8.160000,8.160000,0.0,2.71,0.41,5.04,0.00,36,10,221,773,1863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,05-08-2016,10686,8.110000,8.110000,0.0,1.08,0.20,6.80,0.00,17,4,245,1174,2847
936,05-09-2016,20226,18.250000,18.250000,0.0,11.10,0.80,6.24,0.05,73,19,217,1131,3710
937,05-10-2016,10733,8.150000,8.150000,0.0,1.35,0.46,6.28,0.00,18,11,224,1187,2832
938,05-11-2016,21420,19.559999,19.559999,0.0,13.22,0.41,5.89,0.00,88,12,213,1127,3832
939,05-12-2016,8064,6.120000,6.120000,0.0,1.82,0.04,4.25,0.00,23,1,137,770,1849

In [99]:
df2['ActivityDate']=pd.to_datetime(df2['ActivityDate'])
df2['ActivityDate']

0     2016-04-12
1     2016-04-13
2     2016-04-14
3     2016-04-15
4     2016-04-16
         ...
935   2016-05-08
936   2016-05-09
937   2016-05-10
938   2016-05-11
939   2016-05-12
Name: ActivityDate, Length: 940, dtype: datetime64[ns]

In [100]:
df2.isnull().sum()

ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

In [101]:
df2=df2.set_index('ActivityDate')
df2.head()

,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
ActivityDate,,,,,,,,,,,,,
2016-04-12,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
2016-04-13,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2016-04-14,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
2016-04-15,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
2016-04-16,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863

In [102]:
y=df2['Calories'].resample('D').mean()
y

ActivityDate
2016-04-12    2390.696970
2016-04-13    2286.636364
2016-04-14    2356.393939
2016-04-15    2355.181818
2016-04-16    2392.937500
2016-04-17    2230.968750
2016-04-18    2333.375000
2016-04-19    2359.093750
2016-04-20    2395.218750
2016-04-21    2421.875000
2016-04-22    2327.656250
2016-04-23    2397.156250
2016-04-24    2291.437500
2016-04-25    2349.562500
2016-04-26    2331.375000
2016-04-27    2328.562500
2016-04-28    2316.062500
2016-04-29    2272.562500
2016-04-30    2373.935484
2016-05-01    2230.433333
2016-05-02    2275.448276
2016-05-03    2453.896552
2016-05-04    2283.137931
2016-05-05    2415.068966
2016-05-06    2375.068966
2016-05-07    2246.241379
2016-05-08    2303.444444
2016-05-09    2335.666667
2016-05-10    2229.346154
2016-05-11    2190.083333
2016-05-12    1139.285714
Freq: D, Name: Calories, dtype: float64

In [ ]:
!pip install pmdarima

In [103]:
import pmdarima
from pmdarima.arima import auto_arima
stepwise_model=auto_arima(y,start_p=1,start_q=1,max_p=5,max_q=5,m=12,start_P=0,seasonal=True,d=1,D=1,trace=True,error_action='ignore',suppress_warnings=True,stepwise=True)

Performing stepwise search to minimize aic
 ARIMA(1,1,1)(0,1,1)[12]             : AIC=262.421, Time=0.93 sec
 ARIMA(0,1,0)(0,1,0)[12]             : AIC=256.968, Time=0.16 sec
 ARIMA(1,1,0)(1,1,0)[12]             : AIC=260.457, Time=0.91 sec
 ARIMA(0,1,1)(0,1,1)[12]             : AIC=260.608, Time=1.36 sec
 ARIMA(0,1,0)(1,1,0)[12]             : AIC=258.940, Time=1.78 sec
 ARIMA(0,1,0)(0,1,1)[12]             : AIC=258.940, Time=0.91 sec
 ARIMA(0,1,0)(1,1,1)[12]             : AIC=inf, Time=2.80 sec
 ARIMA(1,1,0)(0,1,0)[12]             : AIC=258.544, Time=0.11 sec
 ARIMA(0,1,1)(0,1,0)[12]             : AIC=258.668, Time=0.65 sec
 ARIMA(1,1,1)(0,1,0)[12]             : AIC=260.514, Time=0.77 sec
 ARIMA(0,1,0)(0,1,0)[12] intercept   : AIC=258.084, Time=0.31 sec

Best model:  ARIMA(0,1,0)(0,1,0)[12]
Total fit time: 10.739 seconds

In [104]:
stepwise_model.aic()

256.9679367388866

In [105]:
stepwise_model.fit(y)

ARIMA(order=(0, 1, 0), scoring_args={}, seasonal_order=(0, 1, 0, 12),
      suppress_warnings=True, with_intercept=False)

In [106]:
future_forecast=stepwise_model.predict(n_periods=8)
future_forecast

2016-05-13     995.783564
2016-05-14    1040.798506
2016-05-15    1219.246782
2016-05-16    1048.488161
2016-05-17    1180.419196
2016-05-18    1140.419196
2016-05-19    1011.591610
2016-05-20    1068.794675
Freq: D, dtype: float64

In [108]:
import pickle
with open('calories.pkl', 'wb') as f:
    pickle.dump(stepwise_model, f)